### ISSUE TITLE
WebOb 1.4 breaks Pylons 1.0.1 redirects.

### ISSUE THREAD

**Issue by Julian-O** [Pylons/pylons#20]
WebObs 1.4 [removes the 'exception' attribute](https://github.com/Pylons/webob/commit/7153f9a2f31c7bf7794e846546a42ec0fe617477) on WSGIHTTPException. It has been deprecated for some time.

This attribute is used by the redirect code, resulting in the following exception:

    Module pylons.controllers.util:224 in redirect  
    >>  raise exc(location=url).exception
    AttributeError: 'HTTPFound' object has no attribute 'exception'

**Comment by bbangert** [comment]
This has been fixed in source, 1.0.2 coming soon.
