### ISSUE TITLE
pylons.controllers.utils.Request.languages() broken

### ISSUE THREAD

**Issue by bcopeland** [Pylons/pylons#24]
With Webob 1.3.1 and Pylons 1.0.1, I get the following:
```
Error - <type 'exceptions.AttributeError'>: 'NilAccept' object has no attribute '_parsed'" while reading upstream
```
The code is relying on an internal attribute which isn't present for all Accept types.  It looks like ab588e7e59a2f44f6b3678db6d735870a385333c introduced this and reverting it makes things work again.

**Comment by bbangert** [comment]
What about Webob 1.4? I'm prepping Pylons 1.0.2 and would like to clear these out, it does kind of suck if various versions of WebOb kept changing this.

**Comment by bcopeland** [comment]
No luck with 1.4:
```
>>> import pylons
>>> x = pylons.controllers.util.Request({})
>>> x.languages()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pylons/controllers/util.py", line 59, in languages
    items = [i for i, q in sorted(al._parsed, key=lambda iq: -iq[1])]
AttributeError: 'NilAccept' object has no attribute '_parsed'
```

Example is contrived, of course, but we did actually hit this path in our fcgi setup; I have wrapped the whole-thing in a try-catch just to work-around for now.

**Comment by bbangert** [comment]
I've pushed 799c310f89f2a81a7c198be18ab98a5f4f17d7ab which should fix this, if someone can try it out before I close this.

**Comment by bcopeland** [comment]
Thanks - looks reasonable, I can throw some actual traffic at it tonight.

**Comment by bcopeland** [comment]
Verified working, thanks!
