### ISSUE TITLE
Update PyPi to 1.0.2

### ISSUE THREAD

**Issue by andrewshadura** [Pylons/pylons#28]
The newly released 1.0.2 version is still not downloadable from PyPi making it difficult to depend on it in setup.py.

**Comment by jvanasco** [comment]
This is updated now.

**Comment by netme** [comment]
Seems to be that there is a small issue with a package on PyPi. 2 directories `/test_files/sample_controllers/i18n` and `/test_files/sample_controllers/templates` are missing. This leads to few failing tests when running `python setup.py test`. Could you please fix the package?

**Comment by netme** [comment]
Moved my question to the issue #32
