### ISSUE TITLE
Some tests fail in non-English locales

### ISSUE THREAD

**Issue by wRAR** [Pylons/pylons#3]
FAIL: test_hello_custom_failed (tests.test_units.test_decorator_validate.TestValidateDecorator)
FAIL: test_hello_failed (tests.test_units.test_decorator_validate.TestValidateDecorator)
FAIL: test_network_failed_validation_non_ascii (tests.test_units.test_decorator_validate.TestValidateDecorator)

That's because these tests expect English error messages and get translated ones. Reproducible in ru_RU.UTF-8 with Pylons 1.0 and git-72f4a5ed

**Comment by bbangert** [comment]
Actually, newer routes seems to handle this, the test works differently now. I've updated it so it reflects reality.
